on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Run Terraform Init
        run: |
          cd terraform
          terraform init
   
      - name: Run Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Upload File to Storage
        run: |
          az storage blob upload --account-name examplestorageaccount --container-name mycontainer --file text.txt --name text.txt
